version: '3.7'

services:
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        - BASE_IMAGE=${PROJECT_NAME}-php:0.0.1
        - UNAME=${UNAME}
    container_name: ${PROJECT_NAME}-devcontainer
    init: true
    hostname: localhost

    working_dir: /workspace
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/workspace:cached
      # Uncomment the next line to use Docker from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker-compose for details.
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.gitconfig:/home/${UNAME}/.gitconfig:ro
      # dont mount .ssh dir here, the ssh-agent has everything we need
      - ~/.ssh/known_hosts:/home/${UNAME}/.ssh/known_hosts

