networks:
  default:
    name: service

services:
  traefik:
    image: traefik:3.2
    platform: linux/amd64
    container_name: service_traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      # listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/service/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./.docker/service/traefik/config:/etc/traefik/conf
  nginx:
    build:
      context: .
      dockerfile: .docker/service/nginx/Dockerfile
    image: service/nginx:0.0.1
    platform: linux/amd64
    container_name: service_traefik_nginx
    restart: unless-stopped
    volumes:
      - ./public:/usr/share/nginx/html
      - ./.docker/service/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      traefik.enable: "true"
      traefik.http.routers.nginx.entrypoints: "web"
      traefik.http.routers.nginx.rule: "Host(`website.localhost`)"
