services:
  cert:
    build: .
    image: service-mkcert:0.0.1
    init: true
    # network_mode: host
    user: ${UID:-1000}
    environment:
      - HOSTOS=${HOSTOS:-}
      - UID=${UID:-1000}
      - GID=${GID:-1000}
    env_file: .cert.env
    volumes:
      - ./certs:/home/${UNAME}/certs
      - ./bin:/home/${UNAME}/bin
